### ISSUE TITLE
DS/R - new form fields for partner selection

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#1074] opened 2018-05-28 12:29 UTC
Add new form fields for partner selection - current implementation is array:

https://project.invisionapp.com/d/main#/console/13903744/289673818/preview

Select partner / justification / justification summary / attachment

**Comment by maciej-jaworski** [comment] 2018-05-29 11:45
Duplicate of #1068.

**Closed** 2018-05-29 11:46 UTC
Labels: ready
