### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by kenzo23312** [unicef/un-partner-portal#462] opened 2017-11-09 09:25 UTC
http://localhost:8080/api/projects/applications/unsolicited/?page=1&page_size=10&project_title=now

Field project_title is not filtering correctly

**Comment by elyk** [comment] 2017-11-09 23:40
@kenzo23312 duplicate of https://github.com/unicef/un-partner-portal/issues/465?

**Comment by lkolacz** [comment] 2017-11-24 11:21
all filtering ('icontains' )project title are done... I go throw all title fields and check

**Closed** 2017-11-24 11:21 UTC
Labels: bug, in progress
