### ISSUE TITLE
V&F Enhancement: Verification Confirmation

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#1170] opened 2018-06-11 19:18 UTC
**Trello Ticket:**
https://trello.com/c/ErvuPMx0/20-verification-confirmation-cr-verification-flagging

**Summary:** Add confirmation to verification modal

**Present Function/Feature:**
If user did a verification and made a mistake, there is no way for the user to delete that verification, so the partner's profile always shows that it was verified at some point which may not be true. A confirmation forces to reviewer to check that they have answered questions correctly

**Enhancement: **
confirmation after selecting ok for verification allowing the user to review their responses.

**Comment by maciej-jaworski** [comment] 2018-08-27 10:48
Duplicate of #1103

**Closed by maciej-jaworski** 2018-08-27 10:48 UTC
Labels: enhancement
