### ISSUE TITLE
Misc/Smaller UI/UX Issues

### ISSUE THREAD

**Issue by elyk** [unicef/un-partner-portal#277] opened 2017-10-20 19:26 UTC
List of smaller UI/UX issues found to keep track of. 

- [x] Partner Registration - Step 1 to Step 2. Width of container changes drastically. [Also from Step 3-4. ](https://www.evernote.com/l/AKLrUE3LSfRNx4wqwa5V62C9IazJnmeCqhw)
- [x] [Partner Registration Org First Name / Last Name Alignment](https://www.evernote.com/l/AKL6SyTQW-lMqY55DT6EYt64D9wW1dBc8nE)
- [x] [NaN-NaN of results to show](https://www.evernote.com/l/AKJ2NTvgwxFGsr-1CDxoXDYfDvMhtB4hgOY) 
- [x] [Display hand icon on all links ](https://www.evernote.com/l/AKLHiO8PE5FCqKEU_mP-pYdRIdFhatdrXDE)
- [x] [Check icons / spacing on Firefox](https://www.evernote.com/l/AKJ5h4QY2_lMJo_mDOwDG7TvqIDeTxFb6Po)

**Comment by marcindo** [comment] 2017-10-24 08:24
Just in case somebody else might work on this, my comments: 
ad.1 Prob needs to set fixed width in vw for the entire paper containing registration, not content dependant
ad. 2 is caused by one label being multiline while other is not, think just aligning to bottom instead top will fix, so setting Grid align property to flex-end
ad. 3 think best is to make index redirect in router to url containing params (need to check how to pass query params to route definition)
ad. 4 instead of clickable table cell, need to insert material-ui typography wrapping react-router Link like in this example: 
```js
<Typography
        component={Link} //wrap react-router Link
        color="accent"
        type="body2"
        to={`/cfei/${type}/${cfeiId}`} // 'to' prop will be passed to Link
      >
        {id}
</Typography>
```
  Already done for  partner applications, but must be added to any text link or table cell we have

**Comment by marcindo** [comment] 2017-10-24 10:39
Some of the 'polar' radio forms with yes-no are bugged and don't display selected value (but it is selected) will be fixed along with partner verifications

**Comment by marcindo** [comment] 2017-10-26 08:04
Ad 5. The highlighted field ( CN id) is clickable and brings to the application, some time ago Kasia mentioned that client only wanted specific cells to be clickable and highlighted with color. @elyk can you confirm that they do indeed want the entire row?

**Comment by marcindo** [comment] 2017-11-02 16:19
ad 3 should be fixed in #387

**Comment by marcindo** [comment] 2017-11-06 10:41
ad. 2 should be fixed in #419

**Comment by elyk** [comment] 2017-11-14 22:48
@marcindo regarding clicking on entire row, I filed another ticket as a question. Will remove from here.

**Comment by marcindo** [comment] 2017-12-13 09:08
Don't see any more spacing issues

**Closed** 2017-12-14 10:30 UTC
Labels: delivered
